name: Publish Python Package to PyPI

on:
  push:
    branches:
      - main # Or 'master', or specific tags like 'v*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Should match your project's Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      # No 'with' section needed if using trusted publishing with OIDC
      # If not using trusted publishing, you would need:
      # with:
      #   user: __token__
      #   password: ${{ secrets.PYPI_API_TOKEN }}

    # Optional: Create a GitHub Release
    # - name: Create GitHub Release
    #   uses: softprops/action-gh-release@v1
    #   if: startsWith(github.ref, 'refs/tags/')
    #   with:
    #     files: dist/*
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
